# Generated by Django 3.1.7 on 2021-05-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210506_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='date_created',
        ),
    ]
